CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=60000

CONFIG_BT_BAS=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

CONFIG_ZMK_SLEEP_PREVENT_WHILE_BLE_CONNECTED=n
CONFIG_ZMK_SLEEP_PREVENT_WHILE_USB_POWERED=y

CONFIG_PROSPECTOR_STATUS_SCREEN_RADII=y
CONFIG_PROSPECTOR_ANIMATION_WPM_REFERENCE=100
CONFIG_PROSPECTOR_LAYER_NAME_UPPERCASE=n
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=75
CONFIG_PROSPECTOR_MODIFIER_ORDER="CSGA"
