manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: newx-it
      url-base: https://github.com/newx-it
    - name: nguyendown
      url-base: https://github.com/nguyendown
    - name: dhruvinsh
      url-base: https://github.com/dhruvinsh
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: carrefinho
      url-base: https://github.com/carrefinho
    - name: quark-works
      url-base: https://github.com/quark-works
  projects:
    - name: zmk
      remote: zmk
      revision: main
      import: app/west.yml
    - name: zmk-auto-layer
      remote: urob
      revision: main # set to same version as zmk above
    - name: zmk-adaptive-key
      remote: urob
      revision: main # set to same as ZMK version above
    - name: zmk-unicode
      remote: urob
      revision: main
    - name: zmk-nice-oled
      remote: newx-it
      revision: main
    - name: zmk-behavior-socd
      remote: nguyendown
      revision: main
    - name: zmk-tri-state
      remote: dhruvinsh
      revision: main
    - name: zmk-behavior-battery-percentage-printer
      remote: badjeff
      revision: main
    - name: prospector-zmk-module
      remote: carrefinho
      revision: feat/new-status-screens
    - name: palindrome-zmk-config
      remote: quark-works
      revision: main
  self:
    path: config
